apiVersion: v1
kind: Service
metadata:
  labels:
    app: billings
  name: billings
spec:
  ports:
    - name: '80'
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: billings
  type: NodePort
