apiVersion: v1
kind: Service
metadata:
  labels:
    app: basket
  name: basket
spec:
  ports:
    - name: '80'
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: basket
  type: ClusterIP
