version: 0.2

env:
  variables:
    DOCKER_PWD: 'DOCKER_PWD'

phases:
  pre_build:
    commands:
      - docker login -u danlevypro -p $DOCKER_PASSWORD
      # - aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 872288361518.dkr.ecr.eu-west-3.amazonaws.com

  build:
    commands:
      - docker build -t front -f ./vite-front/Dockerfile ./vite-front
      - docker tag front danlevypro/front
      # - docker tag front:latest 872288361518.dkr.ecr.eu-west-3.amazonaws.com/front:latest

      - docker build -t gw -f ./apis/apps/gateway/Dockerfile ./apis
      - docker tag gw danlevypro/gw
      # - docker tag gw:latest 872288361518.dkr.ecr.eu-west-3.amazonaws.com/gw:latest

  post_build:
    commands:
      - docker push danlevypro/front
      - docker push danlevypro/gw
      # - docker push 872288361518.dkr.ecr.eu-west-3.amazonaws.com/front:latest
      # - docker push 872288361518.dkr.ecr.eu-west-3.amazonaws.com/gw:latest
