services:
  # front:
  #   image: node:19-alpine
  #   container_name: front_c
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./vite-front:/app
  #   working_dir: /app
  #   command: sh -c "npm install && npm run dev"
  #   env_file:
  #     - ./vite-front/.env

  gateway:
    build:
      context: ./apis
      dockerfile: ./apps/gateway/Dockerfile
    container_name: gateway_c
    hostname: gateway
    command: npm run start:dev gateway
    env_file:
      - ./apis/.env
    # depends_on:
    #   - rabbitmq
    volumes:
      - ./apis:/app
      - /app/node_modules
    ports:
      - '3000:3000'

  products:
    build:
      context: ./apis
      dockerfile: ./apps/products/Dockerfile
    container_name: products_c
    hostname: products
    command: npm run start:dev products
    env_file:
      - ./apis/.env
    # depends_on:
    # - rabbitmq
    volumes:
      - ./apis:/app
      - /app/node_modules
    ports:
      - '3002:3002'

  basket:
    build:
      context: ./apis
      dockerfile: ./apps/basket/Dockerfile
    container_name: basket_c
    hostname: basket
    command: npm run start:dev basket
    env_file:
      - ./apis/.env
    # depends_on:
    # - rabbitmq
    volumes:
      - ./apis:/app
      - /app/node_modules
    ports:
      - '3003:3003'

  payment:
    build:
      context: ./apis
      dockerfile: ./apps/payment/Dockerfile
    container_name: payment_c
    hostname: payment
    command: npm run start:dev payment
    env_file:
      - ./apis/.env
    # depends_on:
    # - rabbitmq
    volumes:
      - ./apis:/app
      - /app/node_modules
    ports:
      - '3004:3004'

  # billings:
  #   build:
  #     context: ./apis
  #     dockerfile: ./apps/billings/Dockerfile
  #   container_name: billings_c
  #   hostname: billings
  #   command: npm run start:dev billings
  #   env_file:
  #     - ./apis/.env
  # depends_on:
  #   - rabbitmq
  # volumes:
  #   - ./apis:/app
  #   - /app/node_modules

  #   rabbitmq:
  #     image: rabbitmq:3-management
  #     container_name: rabbitmq_c
  #     hostname: rabbitmq
  #     volumes:
  #       - /var/lib/rabbitmq
  #     ports:
  #       - '5672:5672'
  #       - '15672:15672'
  #     env_file:
  # - ./apis/.env

  database:
    image: postgres:14-alpine
    container_name: db_c
    hostname: db
    environment:
      - POSTGRES_DB=bando
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
