apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - image: 872288361518.dkr.ecr.eu-west-3.amazonaws.com/payment:latest
          name: payment

          resources:
            limits:
              cpu: '500m'
              memory: '128Mi'
            requests:
              cpu: '250m'
              memory: '64Mi'

          envFrom:
            - secretRef:
                name: back-secrets
