apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment
  name: payment
spec:
  ports:
    - name: '80'
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: payment
  type: NodePort
