apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gw
  name: gw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gw
  template:
    metadata:
      labels:
        app: gw
    spec:
      containers:
        - image: danlevypro/gw:latest
          name: gw

          resources:
            limits:
              cpu: '500m'
              memory: '128Mi'
            requests:
              cpu: '250m'
              memory: '64Mi'
