apiVersion: v1
kind: Service
metadata:
  labels:
    app: gw
  name: gw
spec:
  ports:
    - name: '80'
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: gw
  type: NodePort
