apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deploy
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: danlevypro/front:1.0
          ports:
            - containerPort: 80
          imagePullPolicy: Always

          env:
            - name: VITE_GW_HOSTNAME
              value: gw-service
          resources:
            limits:
              cpu: '500m'
              memory: '128Mi'
            requests:
              cpu: '250m'
              memory: '64Mi'
