apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress

spec:
  ingressClassName: test-front
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-service
                port:
                  number: 80
