name: Publish Docker image

on:
  push:
    branches: [main]

jobs:
  build:
    name: Push images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Front Image
        uses: docker/build-push-action@v4
        with:
          context: ./vite-front
          file: ./vite-front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/front:latest

      - name: GW Image
        uses: docker/build-push-action@v4
        with:
          context: ./apis
          file: ./apis/apps/gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gw:latest
